import type { Metadata } from 'next'
import './globals.css'
import ClientVitals from '@/lib/ClientVitals'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-black">
      <body>
        <ClientVitals />
        {children}
      </body>
    </html>
  )
}
